# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: source/conf.py
  fail_on_warning: true

formats:
- pdf

python:
  install:
  - requirements: requirements.txt

search:
  ranking:
    document/data.html: 10
    document/*: 9
    db/*: 8
    cloud/*: 8
    request/index.html: 7
    image/index.html: 7
    task/index.html: 7
    compress/index.html: 7
    document/plugins/*: 6
    modules/*: 6
    build.html: 6
    references.html: 3
    "*/settings.html": 2
    "*/interface.html": 0
  ignore:
  - index.html
  - versions.html
  - cloud/index.html
  - db/index.html
  - document/index.html
  - document/plugins/index.html
  - modules/index.html
  